// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -988924062,
    "high"
  ],
  /* tuple */[
    -20425611,
    "medium"
  ],
  /* tuple */[
    5395604,
    "low"
  ]
];

function mediaTypeToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function mediaTypeFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -988924062,
    "high"
  ],
  /* tuple */[
    -20425611,
    "medium"
  ],
  /* tuple */[
    5395604,
    "low"
  ]
];

function videoQualityToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function videoQualityFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

var jsMapperConstantArray$2 = /* array */[
  /* tuple */[
    -1055860185,
    "back"
  ],
  /* tuple */[
    109975721,
    "front"
  ]
];

function cameraTypeToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray$2);
}

function cameraTypeFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray$2, param);
}

exports.mediaTypeToJs = mediaTypeToJs;
exports.mediaTypeFromJs = mediaTypeFromJs;
exports.videoQualityToJs = videoQualityToJs;
exports.videoQualityFromJs = videoQualityFromJs;
exports.cameraTypeToJs = cameraTypeToJs;
exports.cameraTypeFromJs = cameraTypeFromJs;
/* No side effect */
